package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
)

const generatedCodeHeader = "// Code generated by gksoap. DO NOT EDIT."

func renderGoFile(pkg string, imports []string, body string) ([]byte, error) {
	if strings.TrimSpace(pkg) == "" {
		return nil, ErrEmptyPackage
	}

	var buf bytes.Buffer
	buf.WriteString(generatedCodeHeader)
	buf.WriteString("\n\npackage ")
	buf.WriteString(pkg)
	buf.WriteString("\n")

	imports = uniqueSorted(imports)
	if len(imports) > 0 {
		buf.WriteString("\n")
		if len(imports) == 1 {
			buf.WriteString(fmt.Sprintf("import %q\n", imports[0]))
		} else {
			buf.WriteString("import (\n")
			for _, path := range imports {
				buf.WriteString(fmt.Sprintf("\t%q\n", path))
			}
			buf.WriteString(")\n")
		}
	}

	trimmedBody := strings.TrimSpace(body)
	if trimmedBody != "" {
		buf.WriteString("\n")
		buf.WriteString(trimmedBody)
		buf.WriteString("\n")
	}

	source, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format go source: %w", err)
	}

	return source, nil
}

func uniqueSorted(values []string) []string {
	if len(values) == 0 {
		return nil
	}

	index := make(map[string]struct{}, len(values))
	items := make([]string, 0, len(values))
	for _, value := range values {
		if _, ok := index[value]; ok {
			continue
		}
		index[value] = struct{}{}
		items = append(items, value)
	}
	sort.Strings(items)
	return items
}
